# Generated by Django 3.2.16 on 2024-04-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20240419_0838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
