# Generated by Django 3.2.16 on 2024-05-03 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipeingredients_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное значение 1.'), django.core.validators.MaxValueValidator(32767, message='Максимальное значение 32767.')], verbose_name='Время готовки в минутах'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Мин. количество ингридиентов 1'), django.core.validators.MaxValueValidator(32767, message='Макс. количество ингридиентов 32767')], verbose_name='Количество'),
        ),
    ]
