# Generated by Django 3.2.16 on 2024-04-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240419_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_for_cook',
            new_name='cooking_time',
        ),
    ]
