# Generated by Django 3.2.16 on 2024-04-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_description_recipe_text'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_name_author',
        ),
    ]
