# Generated by Django 3.2.16 on 2024-04-20 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_recipe_unique_name_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe_ingredients',
            options={'default_related_name': 'recipeingredient', 'ordering': ('recipe',), 'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Количество ингридиентов'},
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_name_measurement_unit',
        ),
        migrations.RemoveConstraint(
            model_name='recipe_ingredients',
            name='unique_recipe_ingredients',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='recipes.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='recipe_ingredients',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe_ingredients',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipeingredient', to='recipes.ingredient', verbose_name='Связанные ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe_ingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipeingredient', to='recipes.recipe', verbose_name='В каких рецептах'),
        ),
    ]
